name: "URL Health Check"
description: "Ping given URL (with curl) for a post-deploy check. With redirect and retrying capabilities"
author: "Roman Nazarenko <me@jtalk.me>, Liza Lukicheva <me@bananamilkshake.me>"
inputs:
  url:
    description: Target URL(s), split by |
    required: true
  max-attempts:
    description: Number of unsuccessful attempts to call URL before giving up
    required: false
    default: "1"
  retry-delay:
    description: Time between attempts (e.g. 3s, 1m)
    required: false
    default: "3s"
  follow-redirect:
    description: Follow redirected location in case request resulted in 3XX status code
    required: false
    default: "false"
  retry-all:
    description: |
      Retry all errors, including 4xx (see man curl on --retry-all-errors).
      This might upgrade curl to the version supporting this flag.
    required: false
    default: "false"
  cookie:
    description: |
      String representation of cookie attached to health check request.
      Format: `Name=Value`
    required: false
    default: ""
  basic-auth:
    description: |
      Basic auth login password pair.
      Format: `login:password`
    required: false
    default: ""
branding:
  icon: check
  color: purple
runs:
  using: "node16"
  main: "dist/index.js"
